version: '2'
services:
  vagrant:
    image: twhtanghk/vagrantvm
    privileged: true
    ports:
      - 1337
    volumes:
      - ./data/run:/var/run/libvirt
      - ./data/lib:/var/lib/libvirt
      - ./data/vm:/usr/src/app/vm/data
      - ./data/exports:/etc/exports
      - ./data/boxes:/root/.vagrant.d/boxes
      - ./data/qemu:/etc/libvirt/qemu
    env_file: 
      - ./.env
      - ../.env
