version: '2'
services:
  vagrant:
    image: dorissschoi/vagrantvm
    privileged: true
    network_mode: host
    volumes:
      - /lib/modules:/lib/modules
      - /var/run/libvirt:/var/run/libvirt
      - /var/lib/libvirt:/var/lib/libvirt
      - ${COMPOSEROOT}/vm/data:/usr/src/app/vm/data
    env_file: 
      - ./.env
      - ../.env
