version: '2'
services:
  ovs:
    image: socketplane/openvswitch
    container_name: ovs
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /lib/modules:/lib/modules
    network_mode: host