version: '2'
services:
  composeui:
    image: francescou/docker-compose-ui
    container_name: composeui
    environment:
      - GIT_REPO=https://github.com/francescou/docker-compose-ui.git
    ports:
      - 5000:5000
    volumes:
      - ..:/opt/docker-compose-projects
      - /var/run/docker.sock:/var/run/docker.sock