version: '2'
services:
  node1:
    image: progrium/consul
    container_name: node1
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8400:8400"
      - "8500:8500"
      - "53:53/udp"
    volumes:
      - ./consul/node1:/data
    command: -server -bootstrap