version: '2'
services:
  ocserv:
    image: tommylau/ocserv
    container_name: ocserv
    hostname: ocserv
    privileged: true
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ${COMPOSEROOT}/ssl/server-cert.pem:/etc/ocserv/server-cert.pem
      - ${COMPOSEROOT}/ssl/server-key.pem/etc/ocserv/server-key.pem